### ISSUE TITLE
web端考勤外勤审批

### ISSUE THREAD

**Issue by houc** [LoyoChengdu/kuaiqi-bugs#1]
web端考勤外勤能自己审批自己的外勤？

**Comment by houc** [comment]
已修复

**Comment by houc** [comment]
考勤外勤不能审批自己的外勤。如果是管理员和普通用户不能审批自己的外勤。他的顺序是超级管理员审批管理员和普通用户的外勤，管理员审批普通用户的外勤。

**Comment by wsyWeb** [comment]
这个需要服务端来判断

**Comment by JoshuaJessery** [comment]
考勤外勤  在没有开启审批的情况下   默认自己审批自己的外勤 并且审批通过

**Comment by houc** [comment]
测试未通过，还是没有好，只是单纯的外勤不存在加班和早退！

**Comment by wsyWeb** [comment]
功能已完成 待测试

**Comment by houc** [comment]
已修复
