### ISSUE TITLE
web端参与人“仅看自己和可看全部”未生效

### ISSUE THREAD

**Issue by houc** [LoyoChengdu/kuaiqi-bugs#13]
建立好一个项目想修改一下参与人的查看权限，在点击某一个人为可看全部却无法生效！需要点击编辑按钮在进行修改权限保存生效。取消在项目时修改“仅看自己和可看全部”，保留删除和增加按钮。。可明白哦

**Comment by wsyWeb** [comment]
已修复  待测试
