### ISSUE TITLE
服务器  CRM  客户信息的动态字段,是否选填,部分客户参数不正确

### ISSUE THREAD

**Issue by goldWave** [LoyoChengdu/kuaiqi-bugs#14]
正式环境
登陆账号:13888888888 密码:123456
可以看见团队和公海客户部分客户信息里面,动态字段是否选填参数不正确.
团队客户里面的customerID: 56d6a492e44c365ae5de8a00
![qq20160303-1](https://cloud.githubusercontent.com/assets/15025129/13482789/16e48cee-e12a-11e5-8d06-87105a8f9023.png)

**Comment by loyozhuhao** [comment]
返回全部信息时，返回值不对，查询详细时，返回值时正确的，已确认使用查询详细信息里面的值，不用修改服务端代码

**Comment by goldWave** [comment]
已经修改
