### ISSUE TITLE
web项目管理、任务计划、工作报告、审批流程上传的附件实际不相符

### ISSUE THREAD

**Issue by houc** [LoyoChengdu/kuaiqi-bugs#17]
项目管理、任务计划、工作报告、审批流程。web端上传附件能正常统计数量，但在移动端上传附件后却不能完全正常显示统计的数量，点击了附件按钮也不会改变。

**Comment by wsyWeb** [comment]
服务器看看

**Comment by goldWave** [comment]
@KonishiLee  附近的bizType貌似没有上传,导致统计数量不符

**Comment by houc** [comment]
第一次上传附件可以正常统计，但删除后统计的数量就不正确了。

**Comment by wahyd4** [comment]
@goldWave  @KonishiLee @mojo-zd  麻烦一起确认下这个应该是谁的问题？

**Comment by KonishiLee** [comment]
@houc 相同的issue就提到同一个嘛

**Comment by wahyd4** [comment]
closed 因为重复
