### ISSUE TITLE
web、IOS、Android端项目管理附件和讨论和实际显示不正确

### ISSUE THREAD

**Issue by houc** [LoyoChengdu/kuaiqi-bugs#18]
在web上传附件在移动端可以正常显示，但是在移动端上传的附件和讨论却需要点击附件按钮才会显示正确的数量，不能实现实时更新？

**Comment by Yyy341** [comment]
正在处理

**Comment by Yyy341** [comment]
Android端 已处理 待测试。

**Comment by houc** [comment]
移动端已正常 web端问题还是有

**Comment by wahyd4** [comment]
@houc  这个和20 差不多吧。请以后提issue的时候，尽量合并哈。  @wsyWeb 麻烦确认下这个bug 是否还存在

**Comment by wahyd4** [comment]
closed 因为重复
