### ISSUE TITLE
web端流程设置

### ISSUE THREAD

**Issue by WANGXUJIAO** [LoyoChengdu/kuaiqi-bugs#2]
设置审批流程最后一个人事经办人时，现在却是同意和驳回

**Comment by houc** [comment]
设置审批流程最后一个人事经办人时，应该为“办结”

**Comment by wsyWeb** [comment]
web端的判断已经完成，但服务端在审批详情与列表中的needApproval参数不一致

另外在项目下获取审批与审批列表中的approvalFlag参数不一致；导致web端的样式不一致

**Comment by JoshuaJessery** [comment]
已经修改了  请测试一下

**Comment by houc** [comment]
已修复
