### ISSUE TITLE
web端设置流程取消两个判断

### ISSUE THREAD

**Issue by houc** [LoyoChengdu/kuaiqi-bugs#33]
设置流程时当选择了职位就不在提示报错选择部门。选择职位也可以保存不需要选择部门。流程判断逻辑如下
如A部门下有B、C员工。B员工是经理，C员工为普通员工，C员工提交了一个审批流程。流程节点为“经理”系统应该先读取部部门职位的经理，如果本部门部门经理没有就读取上属部门经理职位！

**Comment by wsyWeb** [comment]
你来测试一哈

**Comment by houc** [comment]
当多个部门有相同职位时，还是没有读取该部门的职位等级。逻辑判断还是错误
