### ISSUE TITLE
错误bug派重复了，忽略后期修改

### ISSUE THREAD

**Issue by houc** [LoyoChengdu/kuaiqi-bugs#36]
任务计划、项目管理、工作报告参与人上传附件后不能上传附加后不能删除自己的附件了。当所有没有结束时应该有权限删除自己的附件。结束或者完成后才不能上传和删除权限了

**Comment by Yyy341** [comment]
已处理，待测试。

**Comment by houc** [comment]
还未结束项目，参与人上传的附件还是不能删除！结束后才不可以删除。

**Comment by wahyd4** [comment]
@houc  这个是什么意思啊？ 错误bug派重复了，忽略后期修改
