### ISSUE TITLE
web端考勤管理图片取消

### ISSUE THREAD

**Issue by houc** [LoyoChengdu/kuaiqi-bugs#37]
![_c9mr3fs2n8m pzvokuvuf](https://cloud.githubusercontent.com/assets/17491630/13592113/182e0b3a-e52a-11e5-9948-bb6385a7e228.png)

产品组确认把未上传的照片中的图标取消了。有图片才显示图片，没有上传图片就取消

**Comment by wsyWeb** [comment]
测试环境上没有上传附件就不会有图片；可能是服务器在正式环境下没有上传附件也返回了附件Id

**Comment by wahyd4** [comment]
@mojo-zd  这个是因为代码没有部署的原因吗？

**Comment by mojo-zd** [comment]
服务器端如果uuid没有的话  是不会返回uuid的  请确认一下

**Comment by wsyWeb** [comment]
测试环境是对的，没有附件就没有uuid;正式环境没有附件也有uuid

**Comment by mojo-zd** [comment]
android在提交考勤的时候提交了 uuid    @houc   请在内部环境测试一下

**Comment by houc** [comment]
明天测试！！
