### ISSUE TITLE
web、IOS、Android端设置员工生日、微信无法生效

### ISSUE THREAD

**Issue by houc** [LoyoChengdu/kuaiqi-bugs#38]
在web端设置个人生日微信后，移动在通讯录中看不到自己生日！并且在web端的通讯录里面也看不到员工生日微信。web端个人23日，在选择1月时。系统会变成1月1日？

**Comment by wsyWeb** [comment]
微信可以在通讯录中看见， 生日在组织架构创建或更新时没有返回改字段 邮箱字段也未返回

**Comment by loyozhuhao** [comment]
web端已解决没有读取生日信息及微信Id信息

**Comment by goldWave** [comment]
可以测试下

**Comment by houc** [comment]
移动端已经正常了，web通讯录的生日和年龄显示不出来？**web端个人23日，在选择1月时。系统会变成1月1日？**

**Comment by wsyWeb** [comment]
已修复， 待上传测试
