### ISSUE TITLE
web端我的拜访和团队拜访缺少“联系人字段”

### ISSUE THREAD

**Issue by houc** [LoyoChengdu/kuaiqi-bugs#44]
客户拜访里面我的拜访和团队拜访里面差联系人字段。你新加字段后提交给魏诗语！
![default](https://cloud.githubusercontent.com/assets/17491630/13597074/5641fd7e-e551-11e5-8bc9-6df28a9128ac.png)

**Comment by wahyd4** [comment]
这个和#45   应该是因为问题吧

**Comment by KonishiLee** [comment]
@mojo-zd @wahyd4 @loyozhuhao 希望早点提供接口

**Comment by loyozhuhao** [comment]
服务端已返回字段，请前端修改

**Comment by KonishiLee** [comment]
收到
