### ISSUE TITLE
web端考勤详情类型显示不出来

### ISSUE THREAD

**Issue by houc** [LoyoChengdu/kuaiqi-bugs#46]
当员工打了上班卡（并没有迟到）可以显示出来，员工打了上班卡和下班卡或者加班卡考勤详情中的类型就显示不出来了。并且批准了外勤或者加班。不能实时刷新，需要刷新一下网页才可以正常显示？

**Comment by wsyWeb** [comment]
测试环境能显示 , 已修复实时刷新

**Comment by wsyWeb** [comment]
测试环境能显示 , 已修复实时刷新

**Comment by houc** [comment]
无法实时刷新，需求是审批了外勤或者加班点击详情时需要有已确认的显示

**Comment by wsyWeb** [comment]
希望服务器端在审核完成后能将参数返回

**Comment by wahyd4** [comment]
@houc  一个issue 不能既是需求，又是bug 啊 😊

**Comment by mojo-zd** [comment]
@wsyWeb  服务器给你返回了  你看看web需要改东西不  不改请丢给测试

**Comment by wsyWeb** [comment]
修复完成 ， 待测试
