### ISSUE TITLE
web端团队考勤中下拉在最后时点击详情时会自动跳到上页界面

### ISSUE THREAD

**Issue by houc** [LoyoChengdu/kuaiqi-bugs#48]
点击详情后应该定在哪儿不应该跳在上属页面！！！

**Comment by wahyd4** [comment]
![screen shot 2016-03-14 at 00 18 06](https://cloud.githubusercontent.com/assets/836576/13729875/44507622-e97a-11e5-9fa4-8fcbca77a036.png)
 
注意最右上角的滚动条，的确不应该自动滚动到最上面。

@KonishiLee  麻烦解决下这个bug
