### ISSUE TITLE
web团队数据批量操作

### ISSUE THREAD

**Issue by houc** [LoyoChengdu/kuaiqi-bugs#6]
团队客户里面批量操作的标签没有了，参照我的客户标签显示出来。

1. 选择更多选择“参与人”却在详细；列表里面看不到参与人？

**Comment by wsyWeb** [comment]
团队客户里面批量操作的标签没有了，参照我的客户标签显示出来。（已修复）
选择更多选择“参与人”却在详细；列表里面看不到参与人？（提交给马涛）

**Comment by JoshuaJessery** [comment]
已经修改完毕  测试一下
