### ISSUE TITLE
IOS项目管理   垃圾数据

### ISSUE THREAD

**Issue by goldWave** [LoyoChengdu/kuaiqi-bugs#7]
项目里面     报告和审批的数量返回为null
项目id:56cc30220c342edd89000231
正式环境账号:15608001790

**Comment by wahyd4** [comment]
@GongTengFei  麻烦确认下这个是不是bug， 如果不是，请关掉这个issue。

**Comment by GongTengFei** [comment]
@wahyd4 确认不了 暂时不管吧
